apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: biosoftv8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: biosoftv8
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
