apiVersion: v1
kind: Service
metadata:
  name: biosoftv8-service
  labels:
    app: biosoftv8
spec:
  selector:
    app: biosoftv8
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer